src/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('edit/', views.ProfileEdit.as_view(), name='edit'),
    path('<uuid:pk>/post/', views.ProfileDetail.as_view(), name='detail_post'),
    path('<uuid:pk>/post_reply/', views.ProfileDetail.as_view(), name='detail_post_reply'),
    path('<uuid:pk>/media/', views.ProfileDetail.as_view(), name='detail_media'),
    path('<uuid:pk>/like/', views.ProfileDetail.as_view(), name='detail_like'),
    path('follow/', views.FollowControl.as_view(), name='follow'),
    path('unfollow/', views.FollowControl.as_view(), name='unfollow'),
    path('follow-list/<uuid:pk>/', views.FollowList.as_view(), name='followlist'),
    path('follower-list/<uuid:pk>/', views.FollowList.as_view(), name='followerlist'),
    path('deactivate/<uuid:pk>/', views.Deactivate.as_view(), name='deactivate'),
]

src/config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path
from django.urls import include
from django.contrib.staticfiles.urls import static
from . import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    # 以下re_pathまではOAuthを実装していないので、トップへリダイレクトさせる
    path('accounts/email/', RedirectView.as_view(pattern_name='posts:index')),
    path('accounts/inactive/', RedirectView.as_view(pattern_name='posts:index')),
    path('accounts/password/change/', RedirectView.as_view(pattern_name='posts:index')),
    path('accounts/confirm-email/', RedirectView.as_view(pattern_name='posts:index')),
    re_path(r'^accounts/confirm-email/[^/]+/',
        RedirectView.as_view(pattern_name='posts:index'), kwargs=None),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('notifications/', include('notifications.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/notifications/urls.py
from django.urls import path
from . import views

app_name = 'notifications'

urlpatterns = [
    path('', views.notificationsView.as_view(), name='notifications')
]

src/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostIndexView.as_view(), name='index'),
    path('<uuid:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('delete/<uuid:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('like/', views.LikeView.as_view(), name='like'),
    path('unlike/', views.LikeView.as_view(), name='unlike'),
    path('repost/', views.RepostView.as_view(), name='repost'),
    path('unrepost/', views.RepostView.as_view(), name='unrepost'),
    path('bookmark/', views.PostBookmarkView.as_view(), name='bookmark'),
    path('bookmarking/', views.BookmarkView.as_view(), name='bookmarking'),
    path('unbookmarking/', views.BookmarkView.as_view(), name='unbookmarking'),
    path('reply/', views.ajax_reply, name='ajax_reply')
]

src/posts/models.py
import uuid
from django.db import models
from imagekit.models import ImageSpecField
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from imagekit.processors import ResizeToFit


class ObjectsManager(models.QuerySet):
    def all(self):
        return super().all().filter()

    def filter(self, *args, **kwargs):
        where = models.Q(user__is_active=True)
        where &= models.Q(*args, **kwargs)
        return super().filter(where)


class Post(models.Model):
    objects = ObjectsManager.as_manager()
    CHOICES_POST_CATEGORY = [
        (0, '投稿'),
        (1, 'リプライ'),
        (2, 'リポスト'),
    ]
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    user = models.ForeignKey(
        'accounts.CustomUser', 
        verbose_name='ユーザ', 
        on_delete=models.CASCADE)
    title = models.CharField(
        verbose_name='タイトル',
        max_length=20,
        null=True,
        blank=True)
    text = models.TextField(verbose_name='本文')
    photo = models.ImageField(
        verbose_name='投稿画像', 
        null=True,
        blank=True,
        upload_to='images/')
    post_image = ImageSpecField(
        source='photo',
        processors=[ResizeToFit(1080, 1080)],
        format='JPEG',
        options={'quality': 60})
    related_post = models.ForeignKey(
        'self',
        verbose_name='関連投稿',
        null=True,
        blank=True,
        on_delete=models.CASCADE)
    post_category = models.IntegerField(
        verbose_name='分類',
        choices=CHOICES_POST_CATEGORY,
        default=0)
    created_at = models.DateTimeField( 
        auto_now_add=True,
        blank=True)
    updated_at = models.DateTimeField(
        auto_now=True,
        blank=True)
    
    def get_reply(self):
        replies = Post.objects.filter(related_post=self, post_category=1)
        return [reply for reply in replies]

    def get_like(self):
        likes = Like.objects.filter(post=self)
        return [like.user for like in likes]

    def get_repost(self):
        reposts = Post.objects.filter(related_post=self, post_category=2)
        return [repost.user for repost in reposts]

    def get_bookmark(self):
        bookmarks = Bookmark.objects.filter(post=self)
        return [bookmark.user for bookmark in bookmarks]


class Like(models.Model):
    objects = ObjectsManager.as_manager()
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    user = models.ForeignKey(
        'accounts.CustomUser', 
        verbose_name='ユーザ', 
        on_delete=models.CASCADE)
    post = models.ForeignKey(
        'Post',
        verbose_name='投稿', 
        on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'post')

class Bookmark(models.Model):
    objects = ObjectsManager.as_manager()
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    user = models.ForeignKey(
        'accounts.CustomUser', 
        verbose_name='ユーザ', 
        on_delete=models.CASCADE)
    post = models.ForeignKey(
        'Post', 
        verbose_name='投稿', 
        on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'post')

src/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text', 'photo', 'related_post')

src/posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http.response import HttpResponse
from django.http.response import JsonResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.shortcuts import reverse
from django.urls import reverse_lazy
from django.views import generic
from .forms import PostForm
from .models import Like
from .models import Post
from .models import Bookmark
from accounts.models import CustomUser
from accounts.models import Follow
from notifications.models import Notification
from config.settings import LABEL

class PostIndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'index.html'
    paginate_by = 10
    context_object_name = 'posts'

    def get_queryset(self):
        # そのユーザがフォローしている人のIDを取得して代入する
        follow = Follow.objects.filter(follow_from=self.request.user).values_list('follow_to', flat=True)
        # appendできるようにリスト型にキャスト
        display_user = list(follow)
        # 自分の投稿も表示
        display_user.append(self.request.user.id)
        # display_userでfilter
        where = Q()
        where |= Q(post_category=0, user_id__in=display_user)
        where |= Q(post_category=2, user_id__in=display_user)
        posts = Post.objects.filter(where).order_by('-created_at')
        return posts

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['recommend'] = self.get_recommend_user()
        context['label'] = LABEL
        return context

    # おすすめとして表示するユーザーを取得する
    def get_recommend_user(self):
        recommend_user_num = 5 # おすすめのユーザー表示人数
        recommend_user = self.get_recent_post_user()
        # ログイン中のユーザーがフォローしている人リスト
        follow = Follow.objects.filter(follow_from=self.request.user).values_list('follow_to', flat=True)
        # フォローしている人は除外
        recommend_user = recommend_user.exclude(id__in=follow)
        # 自分は除外
        recommend_user = recommend_user.exclude(id=self.request.user.id)
        # 表示人数のみ取得
        recommend_user = recommend_user[:recommend_user_num]
        return recommend_user

    # 最近ポストしたユーザーを取得する
    def get_recent_post_user(self):
        recent_post_user = (
            Post.objects.all()
            .order_by('-created_at')
            .values_list('user_id', flat=True).order_by('user_id').distinct()
        )
        recent_post_user = CustomUser.objects.filter(id__in=recent_post_user)
        return recent_post_user

class PostDetailView(LoginRequiredMixin, generic.DetailView):
    model = Post
    template_name = "detail.html"
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["posts"] = Post.objects.filter(
            related_post=self.kwargs['pk'],
            post_category=1
        ).order_by('-id')
        return context


class PostBookmarkView(LoginRequiredMixin, generic.ListView):
    template_name = 'bookmark.html'
    paginate_by = 10
    context_object_name = 'posts'

    def get_queryset(self):
        bookmarks = Bookmark.objects.filter(user=self.request.user).values('post_id').order_by('id')
        posts = Post.objects.filter(id__in=bookmarks).order_by('-created_at')
        return posts


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = PostForm
    reply_category_no = 1

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if self.request.POST.get('action') == 'post':
            form.instance.user_id = self.request.user.id
            messages.success(self.request, '投稿が完了しました。')
            return super(PostCreateView, self).form_valid(form)
        elif self.request.POST.get('action') == 'reply':
            self.object.text = form.cleaned_data['text']
            self.object.related_post_id = self.request.POST.get('related_post_id')
            self.object.post_category = self.reply_category_no
            form.instance.user_id = self.request.user.id
            return super(PostCreateView, self).form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, '投稿が失敗しました。')
        return redirect('posts:index')

    def get_success_url(self):
        if self.request.POST.get('action') == 'post':
            return reverse('posts:index')
        elif self.request.POST.get('action') == 'reply':
            return reverse('posts:detail', kwargs={'pk': self.object.related_post_id})


class PostDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Post
    success_url = reverse_lazy('posts:index')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user == request.user:
            messages.success(self.request, '削除しました。')
        return super().delete(request, *args, **kwargs)


class LikeView(LoginRequiredMixin, generic.View):
    model = Like
    NOTIFICATION = '{}さんがあなたの投稿にいいねしました。'

    def post(self, request):
        post_id = request.POST.get('id')
        post = Post.objects.get(id=post_id)
        user = self.request.user
        if request.path == '/like/':
            Like(user=user, post=post).save()
            like_count = Like.objects.filter(post=post).count()
            data = {
                'like_count': like_count
            }
            # お知らせ作成
            Notification(
                text=self.NOTIFICATION.format(user),
                user=post.user,
                action_user=user
            ).save()
        else:
            like = Like.objects.get(user=user, post=post).delete()
            like_count = Like.objects.filter(post=post).count()
            data = {
                'like_count': like_count
            }

        return JsonResponse(data)


class RepostView(LoginRequiredMixin, generic.View):
    model = Post
    repost_category_no = 2
    NOTIFICATION = '{}さんがあなたの投稿をリポストしました。'

    def post(self, request):
        post_id = request.POST.get('id')
        post = Post.objects.get(pk=post_id)
        user = self.request.user
        data = {}
        if request.path == '/repost/':
            Post(
                user=user,
                related_post_id=post_id,
                post_category=self.repost_category_no
                ).save()
            # お知らせ作成
            Notification(
                text=self.NOTIFICATION.format(user),
                user=post.user,
                action_user=user
            ).save()
        else:
            Post.objects.get(
                user=user,
                related_post_id=post_id,
                post_category=self.repost_category_no
                ).delete()

        return JsonResponse(data)

class BookmarkView(LoginRequiredMixin, generic.View):
    model = Bookmark

    def post(self, request):
        post_id = request.POST.get('id')
        post = Post.objects.get(id=post_id)
        user = self.request.user
        if request.path == '/bookmarking/':
            Bookmark(user=user, post=post).save()
        else:
            Bookmark.objects.get(user=user, post=post).delete()
        return JsonResponse({})

def ajax_reply(request):
    pk = request.GET.get('pk')
    post = Post.objects.get(pk=pk)
    replies = post.post_set.all().order_by('id')
    return render(request, 'posts.html', {'posts': replies})

src/posts/templates/base.html
{% load static %}
{% load bootstrap4 %}
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://kit.fontawesome.com/f8452db4da.js" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'Croppie/croppie.css' %}" />
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-4YJ6RZ9LFL"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-4YJ6RZ9LFL');
    </script>
    <!-- / Global site tag (gtag.js) - Google Analytics -->
  </head>

  <body>



    {% if user.is_authenticated %}
    <!-- 投稿 モーダル -->
    <div class="modal fade" id="postModal" tabindex="-1" role="dialog" aria-labelledby="postModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="postModalLabel">新規投稿</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form method="post" action="{% url 'posts:create' %}" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form-group">
                <input class="form-control" id="postFormControlInput" name="title" placeholder="タイトル">
              </div>
              <div class="form-group">
                <textarea class="form-control" id="postFormControlTextarea" name="text" rows="5" placeholder=""></textarea>
              </div>
              <div class="form-group mt-1">
                <label for="postFormControlFile" class="hover-opacity60"><i class="far fa-images fa-2x"></i> 画像を選択</label>
                <input type="file" class="form-control-file" id="postFormControlFile" name="photo">
              </div>
              <button class="btn btn-main btn-block" type="submit" name="action" value="post">送信</button>
            </form>
          </div>
        </div>
      </div>
    </div>
    {% endif %}
    <main role="main" class="container">
      <header class="top-menu-bar">
        <a class="navbar-brand title-font" href="{% url 'posts:index' %}"><h1>Jazz達</h1></a>
        <a class="btn btn-light" href="#"><i class="fas fa-bars"></i></a>
      </header>
      <div class="row mt-lg-5 mt-3">
        <div class="col-lg-4 side-menu-bar mt-3" style="overflow: hidden;">
          <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item hover-opacity60">
              <a class="navbar-brand title-font" href="{% url 'posts:index' %}"><h1>Jazz達</h1></a>
            </li>
            <li class="nav-item hover-opacity60">
              <a class="nav-link" href="{% url 'accounts:detail_post' user.id %}">
                <i class="fas fa-lg fa-user"> {{ user.nickname | truncatechars:8 }}</i>
              </a>
            </li>
            <li class="nav-item hover-opacity60">
              <a class="nav-link" href="{% url 'posts:index' %}">
                <i class="fas fa-lg fa-home mr-3"></i>HOME
              </a>
            </li>
            <li class="nav-item hover-opacity60">
              <a class="nav-link" data-toggle="modal" data-target="#postModal" data-whatever="@mdo" href="{% url 'posts:index' %}">
                <i class="fas fa-lg fa-pencil-alt mr-3"></i>POST
              </a>
            </li>
            <li class="nav-item hover-opacity60">
              <a class="nav-link" href="{% url 'notifications:notifications' %}">
                <i class="far fa-lg fa-bell mr-3"></i>NOTIFICATIONS
              </a>
            </li>
            <li class="nav-item hover-opacity60">
              <a class="nav-link" href="{% url 'posts:index' %}">
                <i class="far fa-lg fa-envelope mr-3"></i>MESSAGES
              </a>
            </li>
            <li class="nav-item hover-opacity60">
              <a class="nav-link" href="{% url 'posts:bookmark' %}">
                <i class="far fa-lg fa-bookmark mr-3"></i>BOOK MARKS
              </a>
            </li>
            <li class="nav-item hover-opacity60">
              <a class="nav-link" href="{% url 'account_logout' %}">
                <i class="fas fa-sign-out-alt mr-3"></i>LOGOUT
              </a>
            </li>
            {% block deactivate %}{% endblock %}
            {% else %}
            <li class="nav-item hover-opacity60">
              <a class="navbar-brand title-font" href=""><h1>Jazz達</h1></a>
            </li>
              {% block login %}{% endblock %}
              {% block signup %}{% endblock %}
            <li class="nav-item hover-opacity60">
              <a class="btn btn-main" data-toggle="modal" data-target="#topModal" data-whatever="@mdo" href="">
                {% block enter %}{% endblock %}
              </a>
            </li>
          {% endif %}
          </ul>
        </div>
        <div class="col-lg-8 message-template">
          {% if messages %}
          <div class="w-100">
            <ul class="posts-base-messages">
              {% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}
              </li>
              {% endfor %}
            </ul>
          </div>
          {% endif %}
          {% block contents %}{% endblock %}
        </div>
      </div>
    </main>
  
    <!-- /.container -->
    <p class="mt-5 mb-3 text-muted text-center">&copy; 2021 Jazz達</p>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'js/base.js' %}"></script>
    <script src="{% static 'Croppie/croppie.js' %}"></script>
  </body>
</html>

src/posts/templates/bookmark.html
{% extends 'base.html' %}
{% load static %}
{% block title %}ブックマーク | Jazz達{% endblock %}
{% block contents %}

{% if posts %}
  {% include 'posts.html' %}
{% else %}
  <ul class="posts-base-messages">
    <li class="alert alert-warning">ブックマークはありません</li>
  </ul>
{% endif %}

<nav>
  <ul class="pagination justify-content-center mt-5">
  {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link text-info" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">&laquo;</a>
    </li>
  {% else %}
    <li class="page-item disabled"><span class="page-link">
      &laquo;</span></a>
    </li>
  {% endif %}
  {% for i in page_obj.paginator.page_range %}
  {% if page_obj.number == i %}
    <li class="page-item disabled"><span class="page-link">{{ i }}</span></li>
  {% else %}
    <li class="page-item"><a class="page-link text-info" href="?page={{ i }}">{{ i }}</a></li>
  {% endif %}
  {% endfor %}
  {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link text-info" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
    </li>
  {% else %}
    <li class="page-item disabled">
      <span class="page-link">&raquo;</span>
    </li>
  {% endif %}
  </ul>
</nav>
{% endblock %}

src/posts/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ post.user.nickname }}の投稿 | Jazz達{% endblock %}
{% block contents %}

<div class="card text-left">
  <div class="card-body">
    <div class="d-flex">
      <div>
        <a href="{% url 'accounts:detail_post' post.user.id %}"><img src="{% if post.user.thumbnail %}{{ post.user.thumbnail.url }}{% else %}{% static 'images/no_photo.png' %}{% endif %}" class="rounded-circle profile-post-photo"></a>
      </div>
      <div class="ml-3">
        <a href="{% url 'accounts:detail_post' post.user.id %}" class="post-main-text text-white hover-opacity60">{{ post.user.nickname }}</a><br>
        <small class="text-muted">{{ post.created_at | date:"n月j日 H時i分" }}</small>
      </div>
    </div>
    <div class="my-3">
      <a href="{% url 'posts:detail' post.pk %}" class="post-main-text text-white">{% if post.title %}{{ post.title }}{%else %}title{% endif %}</a>
    </div>
    {% if post.post_image %}
    <img class="post-image" src="{{ post.post_image.url }}" alt="投稿画像" />
    {% endif %}
    <p class="card-text mt-2">{{ post.text | linebreaks }}</p>
    <!-- リプライ, いいね など -->
    <div class="post-flex-action my-2">
        <div class="post-flex-reply" data-toggle="modal" data-target="#replyModal-{{ post.id }}" data-whatever="@mdo" onclick="return false;">
            <div class="btn reply-link p-0">
                <i class="far fa-comment post-icon hover-opacity60 text-white"></i>
            </div>
            <span class="badge" onclick="javascript:showReply({{ post.pk }}, {{ post.get_reply | length }}); return false;">{{ post.get_reply | length }}</span>
        </div>
        <div class="post-flex-like btn-like" onclick="return false;">
            <button class="btn btn-link p-0 {% if user in post.get_like %}post-liked{% else %}post-like{% endif %} post-like-{{ post.id }}" data-id="{{ post.id }}">
                <i class="fab fa-itunes-note hover-opacity60"></i>
            </button>
            <span class="badge like-count-{{ post.id }}">{{ post.get_like | length }}</span>
        </div>
        <div class="post-flex-repost btn-repost" onclick="return false;">
            <button class="btn btn-link p-0 {% if user in post.get_repost %}post-reposted{% else %}post-repost{% endif %} post-repost-{{ post.id }}" data-id="{{ post.id }}">
                <i class="fas fa-retweet hover-opacity60"></i>
            </button>
        </div>
        <div class="post-flex-dropdown" onclick="return false;">
            <div data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v text-white"></i>
            </div>
            <div class="dropdown-menu">
                <div class="dropdown-item jz-btn-bookmark{% if user in post.get_bookmark %} jz-bookmarked{% endif %}" data-id="{{ post.id }}">
                    {% if user in post.get_bookmark %}
                    ブックマークから外す
                    {% else %}
                    このポストをブックマークする
                    {% endif %}
                </div>
            </div>
            <!--
            <div class="dropdown-menu">
                <a class="dropdown-item" href="#">{{ post.user }}さんをフォローする</a>
                <a class="dropdown-item" href="#">{{ post.user }}さんをブロックする</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">通報する</a>
            </div>
            -->
        </div>
        {% if post.user.id == user.id %}
        <div class="post-flex-delete">
            <form method="post" action="{% url 'posts:delete' post.id %}" class="d-inline">
                {% csrf_token %}
                <button class="btn btn-link text-info p-0 hover-opacity60" type="submit" onclick='return confirm("この投稿を本当に削除しますか？"); return false;'>
                    <i class="far fa-trash-alt text-white"></i>
                </button>
            </form>
        </div>
        {% endif %}
    </div>
  </div>
</div>
<hr>
{% include 'posts.html' %}

<!-- reply モーダル -->
<div class="modal fade" id="replyModal-{{ post.id }}" tabindex="-1" role="dialog" aria-labelledby="postModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="postModalLabel">リプライ</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>{{ post.text | truncatechars:40 }}</p>
        <form method="post" action="{% url 'posts:create' %}" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            <textarea class="form-control" id="postFormControlTextarea" name="text" rows="5" placeholder=""></textarea>
          </div>
          <button class="btn btn-main btn-block" type="submit" name="action" value="reply">リプライ</button>
          <input type="hidden" name="related_post_id" value="{{ post.id }}">
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

src/posts/templates/post_reply_modal.html
<!-- reply モーダル -->
<div class="modal fade" id="replyModal-{{ post.id }}" tabindex="-1" role="dialog" aria-labelledby="postModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="postModalLabel">リプライ</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>{{ post.text | truncatechars:40 }}</p>
                <form method="post" action="{% url 'posts:create' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <textarea class="form-control" id="postFormControlTextarea" name="text" rows="5" placeholder=""></textarea>
                    </div>
                    <div class="mx-auto">
                        <button class="btn btn-main btn-block text-center" type="submit" name="action" value="reply">リプライ</button>
                    </div>
                    <input type="hidden" name="related_post_id" value="{{ post.id }}">
                </form>
            </div>
        </div>
    </div>
</div>